### ISSUE TITLE
thêm nguồn truyentranhaudio.online

### ISSUE THREAD

**Issue by giangdhVidaGIS** [Darkrai9x/extensions#1]
nhờ chủ thớt thêm nguồn https://truyentranhaudio.online/

**Comment by Darkrai9x** [comment]
Đã chập nhật nha bạn

**Comment by giangdhVidaGIS** [comment]
![Thank-you](https://user-images.githubusercontent.com/22956299/91245591-0a1d3700-e778-11ea-911c-a529e3a27a3e.jpg)
